### ISSUE TITLE
Running time Logodds computation

### ISSUE THREAD

**Issue by hcordoba** [Rostlab/VESPA#7]
Hi, I am trying VESPA on a dataset with ~27K proteins on a GPU machine with enough memory and cores. How long should this process last? It has been around 40 hours.

I would appreciate some ideas as it seems to be running, but maybe something was not correctly set.

Thanks

**Comment by mheinzinger** [comment]
Hi,
if you need scores for more than a few proteins, I would strongly recommend to use VESPAl which is MUCH faster than VESPA. VESPAl drops the logodds computation (which is our speed-bottleneck) and relies mostly on the predicted conservation scores.
Despite being orders of magnitude faster, VESPAl performs only slightly worse than VESPA.
So for 27k proteins, I would clearly go for VESPAl because VESPA will take weeks/months.

**Comment by hcordoba** [comment]
Hi Michael!

Thank you for your prompt response and advice.
